"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("reflect-metadata");
const inversify_1 = require("inversify");
const types_1 = require("./types");
const bot_1 = require("./bot");
const discord_js_1 = require("discord.js");
const message_responder_1 = require("./services/message-responder");
const ping_finder_1 = require("./services/ping-finder");
const music_1 = require("./services/music");
const league_1 = require("./services/league");
const osu_1 = require("./services/osu");
let container = new inversify_1.Container();
container.bind(types_1.TYPES.Bot).to(bot_1.Bot).inSingletonScope();
container.bind(types_1.TYPES.Client).toConstantValue(new discord_js_1.Client());
container.bind(types_1.TYPES.Token).toConstantValue(process.env.TOKEN);
container.bind(types_1.TYPES.Prefix).toConstantValue(process.env.PREFIX);
container.bind(types_1.TYPES.MysqlHost).toConstantValue(process.env.MYSQLHOST);
container.bind(types_1.TYPES.MysqlPort).toConstantValue(process.env.MYSQLPORT);
container.bind(types_1.TYPES.MysqlUser).toConstantValue(process.env.MYSQLUSER);
container.bind(types_1.TYPES.MysqlPassword).toConstantValue(process.env.MYSQLPASSWORD);
container.bind(types_1.TYPES.MysqlDatabase).toConstantValue(process.env.MYSQLDATABASE);
container.bind(types_1.TYPES.Calendar).toConstantValue(process.env.CALENDAR);
container.bind(types_1.TYPES.RiotAPIKey).toConstantValue(process.env.RIOT_API_KEY);
container.bind(types_1.TYPES.OsuAPIKey).toConstantValue(process.env.OSU_API_KEY);
container.bind(types_1.TYPES.MessageResponder).to(message_responder_1.MessageResponder).inSingletonScope();
container.bind(types_1.TYPES.PingFinder).to(ping_finder_1.PingFinder).inSingletonScope();
container.bind(types_1.TYPES.Music).to(music_1.Music).inSingletonScope();
container.bind(types_1.TYPES.League).to(league_1.League).inSingletonScope();
container.bind(types_1.TYPES.Osu).to(osu_1.Osu).inSingletonScope();
exports.default = container;
//# sourceMappingURL=inversify.config.js.map