export const TYPES = {
  Bot: Symbol("Bot"),
  Client: Symbol("Client"),
  Token: Symbol("Token"),
  Prefix: Symbol("Prefix"),
  MysqlHost: Symbol("MysqlHost"),
  MysqlPort: Symbol("MysqlPort"),
  MysqlUser: Symbol("MysqlUser"),
  MysqlPassword: Symbol("MysqlPassword"),
  MysqlDatabase: Symbol("MysqlDatabase"),
  Calendar: Symbol("Calendar"),
  MessageResponder: Symbol("MessageResponder"),
  PingFinder: Symbol("PingFinder"),
  Music: Symbol("Music"),
  League: Symbol("League"),
  Osu: Symbol("Osu"),
  RiotAPIKey: Symbol("RiotAPIKey"),
  OsuAPIKey: Symbol("OsuAPIKey"),
};